/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomLayer: typeof import('./components/site_editor/BottomLayer.vue')['default']
    Breadcrumb: typeof import('./components/functional/breadcrumb.vue')['default']
    Chat: typeof import('./components/functional/chat/chat.vue')['default']
    ChatContact: typeof import('./components/functional/chat/chat-contact.vue')['default']
    CloseButton: typeof import('./components/functional/close-button.vue')['default']
    Drawer: typeof import('./components/functional/drawer.vue')['default']
    EditIcon: typeof import('./components/functional/icons/EditIcon.vue')['default']
    Grid: typeof import('./components/functional/grid/Grid.vue')['default']
    Header: typeof import('./components/functional/chat/partials/header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LinkButton: typeof import('./components/functional/buttons/LinkButton.vue')['default']
    PageComponent: typeof import('./components/page/PageComponent.vue')['default']
    PageComponentContainer: typeof import('./components/page/PageComponentContainer.vue')['default']
    PageEditor: typeof import('./components/page/PageEditor.vue')['default']
    PrimaryButton: typeof import('./components/functional/buttons/PrimaryButton.vue')['default']
    RenderedPage: typeof import('./components/site_editor/RenderedPage.vue')['default']
    RightMenu: typeof import('./components/site_editor/RightMenu.vue')['default']
    RoundedPlus: typeof import('./components/icons/RoundedPlus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteMap: typeof import('./components/site_editor/SiteMap.vue')['default']
    SiteMapView: typeof import('./components/site_editor/SiteMapView.vue')['default']
    SitePageTree: typeof import('./components/SitePageTree.vue')['default']
    Spinner: typeof import('./components/functional/spinner.vue')['default']
    SvgFlag: typeof import('./components/functional/svg-icons/svg-flag.vue')['default']
    SvgIcon: typeof import('./components/functional/svg-icons/svg-icon.vue')['default']
    TopLayer: typeof import('./components/site_editor/TopLayer.vue')['default']
    TopNav: typeof import('./components/site_editor/TopNav.vue')['default']
    Wireframe: typeof import('./components/site_editor/Wireframe.vue')['default']
    Zoomer: typeof import('./components/Zoomer.vue')['default']
  }
}
